### ISSUE TITLE
RKE v1.0.0 released

### ISSUE THREAD

**Issue by carnivorelogic** [rancher/terraform-provider-rke#125]
Time for terraform-provider-rke version bump as well?

**Comment by insekticid** [comment]
This release comes with the latest Kubernetes versions, i.e. v1.13.12, v1.14.8, v1.15.5, for Rancher launched Kubernetes clusters to address the CVE-2019-11253 and CVE-2019-16276. Rancher recommends upgrading all Kubernetes clusters to these Kubernetes versions.

**Comment by tlvenn** [comment]
RKE 0.3.2 is out as well now.

**Comment by jbmcfarlin31** [comment]
@yamamoto-febc is there any timeline on when this will be updated?

**Comment by tlvenn** [comment]
Well maybe more importantly, do you need help with this @yamamoto-febc ?

**Comment by jodett** [comment]
I would be very interested in an update too, are there any plans?

**Comment by tlvenn** [comment]
The project has been transferred to Rancher, it would be great if someone from Rancher could clarify what is going... @superseb @ibuildthecloud @vincent99 

Thanks !

**Comment by jbmcfarlin31** [comment]
@cloudnautique @Oats87 since the repo has been officially transferred to Rancher, is there any update as to when it will be updated with the latest RKE/K8s releases? 

We are a huge user of this provider, and depend on it a lot. Thanks!

**Comment by tlvenn** [comment]
I am kinda speechless at the total lack of communication on this....
Come on guys, it's been 2 months that the community is trying to understand what is going on...

**Comment by cloudnautique** [comment]
Hi All,

 I apologize for the delay in getting information out about the provider. We are excited to take over the project. Our plan, in short, is to bring the versions up to date and also get it officially supported as a TF provider. (In short we want `terraform init` to work!)

 Right now we are winding down a few projects in order to get to work on this, and it will take us a couple weeks to be able to dive in. It sounds like updating the RKE version is the most pressing thing,  so we will aim to prioritize that first. 

Thank you for your patience.

**Comment by tlvenn** [comment]
Hi @cloudnautique,

Thanks for the update, would you accept a PR that would simply link to the latest RKE ? Something similar to this https://github.com/rancher/terraform-provider-rke/commit/1e6df18f743f011f89cb2fc01315933977a2b46a ?

**Comment by jbmcfarlin31** [comment]
> Hi @cloudnautique,
> 
> Thanks for the update, would you accept a PR that would simply link to the latest RKE ? Something similar to this [1e6df18](https://github.com/rancher/terraform-provider-rke/commit/1e6df18f743f011f89cb2fc01315933977a2b46a) ?

@tlvenn In my repo I managed to get RKE up to I think `v0.3.0`, but when I tried bumping it to `v0.3.2` a lot of dependencies started breaking - and being that I am still fairly new to Go, I didn't know where to start. So if @cloudnautique would accept a PR bumping it temporarily to even `v0.3.0` that would be great as well!

Also @cloudnautique thanks for the reply. We (and I assume many others) are eagerly awaiting `v1`! Let us know if we can be of assistance in helping propel the provider forward.

**Comment by cloudnautique** [comment]
@tlvenn, our current understanding is that the version bump is more significant than the change above. There were schema changes and CSI options that were added to RKE and the impact to the provider is not currently known by us at the moment. 

@jbmcfarlin31, if v0.3.0 would help move things forward, we would certainly review a PR. The hesitation there is we don't have this project setup into our CI infrastructure yet. So not sure if we would be able to sufficiently test. We would need community assistance to get anything verified quickly.

**Comment by injectedfusion** [comment]
I'll be willing to help in the testing process!

**Comment by jbmcfarlin31** [comment]
Hey guys (@insekticid , @carnivorelogic , @tlvenn , @jodett ) just to update here... I forked the repo and with the help of my team managed to bump the RKE provider to RKE `v1.0.0`. I have a test cluster deployed on Azure Stack, everything seems to be working as intended - see output:
```
NAME            STATUS   ROLES                      AGE   VERSION
node1           Ready    controlplane,etcd,worker   40m   v1.16.3
```
I have not posted the provider as a release or anything, but in order to get the provider built I have just been utilizing the `GNUMakefile` associated with the project and running `make build`.

If the community is willing to test and @cloudnautique would accept a PR after testing, or before in a new branch, then we might could get this implemented.

Let me know, hope this works for y'all!

**Comment by carnivorelogic** [comment]
Community is ready for the test 😊.

**Comment by cloudnautique** [comment]
We have our first PR: #142 inflight.

**Comment by rawmind0** [comment]
Hi all,

yesterday, we published our first provider prerelease supporting RKE 1.0.0 [v1.0.0-rc1](https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0-rc1)

Feedback is more than appreciate. 

Thanks for your patience.
