### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by vitobotta** [rancher/terraform-provider-rke#135]
Hi! I just started experimenting with this provider (I'm also new to Terraform in general). I got a cluster up and running and I have also tested adding nodes which works fine. 

A few questions:

- the version of kubernetes is still 1.14 though. How does upgrading work? What do I need to do to upgrade Kubernetes when a new version of this provider is available? 

- it looks like I can't set the s3 bucket `folder` for etcd backups, which is among the currently possible settings with RKE. Is this because of the version of RKE in use by the provider?

- I can't set `canal_network_provider`/`iface` to ensure that all traffic goes through a specific network interface - not entirely sure if this is still needed when specifying internal IPs.

- after creating the cluster, I don't see an rkestate file. Where is it? Or is it not needed when using this provider? Where is the RKE state stored?

- how can I take manual etcd snapshots or restore from existing snapshot?

Thanks a lot! This provider is very useful.

**Comment by shaunc** [comment]
Also want to know how to upgrade kubernetes version, and learn how to use backups. 

Looking at the RKE doc, I'm guessing that to upgrade kubernetes version, one would first output the cluster.yml, modify to specify kubernetes version wanted, then specify that cluster.yml as a resource. Is that correct?

It would be great if the options in the cluster.yml could be directly specified in the rke_cluster resource.

**Comment by jbmcfarlin31** [comment]
Hi @vitobotta 

1) To my understanding for upgrading a cluster, and the way I have done it in the past, is I specify in my `rke.tf` file the kubernetes version, for example you can do the following in the `cluster` resource within terraform: `  kubernetes_version = "v1.15.3-rancher1-1"`.

    So when a new version of the rke provider comes out, and upgrades the kubernetes version, I simply change that value to whatever the default is and re-run the `terraform plan && terraform apply` commands. This will upgrade the cluster in place without taking it down.

2) For etcd backups and configuring, checkout the [full example](https://github.com/rancher/terraform-provider-rke/blob/master/examples/full/example.tf#L133-L153) section where you can specify etcd specific configurations if you haven't already.

3) The CNI provider for RKE can be `canal/calico/flannel/weave`. This can be specified in the `rke.tf` file as well, see the [full example](https://github.com/rancher/terraform-provider-rke/blob/master/examples/full/example.tf#L245-L247). As far as explicitly defining what interface traffic goes through, I don't think that is possible - but I am also not entirely sure on your question either.

4) RKE statefile exists only when creating the cluster during the `terraform apply` command. Once the cluster has been created, the RKE state is stored within the default `terraform.tfstate` file for that terraform deployment.

5) Manual etcd snapshots and backups would have to be done outside of the RKE provider - once the cluster has been configured. You would SSH to one of the management nodes, run a `docker ps` to see if `etcd` is running as a container (which it should) - and then `docker exec -it etcd` and perform the backup commands there.

I hope this helps clear up some questions and/or thoughts!

As for @shaunc ; you might want to checkout the [full example](https://github.com/rancher/terraform-provider-rke/blob/master/examples/full/example.tf) as well, because there hasn't been anything that regular RKE allows me to do that I haven't been able to do inside of the terraform provider `rke_cluster` resource.
