### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by gyalowitzdtlr** [rancher/terraform-provider-rke#224]
I am in the middle of a k8 deployment onto vsphere using Terraform with the RKE provider.  It plans out ok, but after deploying the virtual machines, the deployment errors out.  After re-planning and applying again, the cluster spins up without an issue.  Is this an issue with Terraform and RKE spinning up in the same apply?  This is the error 
 **Error**
![inconsistant_plan](https://user-images.githubusercontent.com/59739698/86551878-5be1d780-bf14-11ea-9f81-36504a1b97c6.png)
**Terraform Versions**
![terraform_versions](https://user-images.githubusercontent.com/59739698/86553368-8fbefc00-bf18-11ea-8af9-d555cfdec275.png)

**Comment by rawmind0** [comment]
It seems you have a tf dependency problem, nodes are changing from 2 to 8 during execution

**Comment by loizoskounios** [comment]
I have the same issue.

I am adding / removing nodes dynamically by utilising Terraform's dynamic block construct to generate the `nodes` block:

```tf
resource "rke_cluster" "this" {

  ...

  dynamic "nodes" {
    for_each = var.spec

    content {
      role = nodes.value.role == "master" ? ["controlplane", "etcd"] : ["worker"]

      address           = nodes.key
      internal_address  = nodes.key
      hostname_override = nodes.key

      user    = nodes.value.ssh_user
      ssh_key = nodes.value.ssh_key
    }
  }

  ...

}
```

`var.spec` is a map whose key is the IP address RKE should use to reach said machines:

```tf
variable "spec" {
  type = map(object({
    role = string

    ssh_user = string
    ssh_key  = string
  }))
}
```

In my case, the RKE Terraform provider (v1.0.1) plans for 1 node only even though there are multiple nodes to begin with and the spec has changed to include more nodes.

For example, I have 6 nodes running and I want to add 3 more. The RKE provider's proposed changes suggest that only 1 node is kept. The 3 new instances are created in the meantime since RKE depends on them. Then RKE's initial plan is checked against the state and Terraform finds that the number of `nodes` blocks that was initially planned is 1, but now, with the new data taken into account, it is 9. Terraform halts execution.

If I run `terraform apply` again, RKE does the right thing. I'm not sure what's causing the issue because everything works correctly when creating a fresh cluster. The provider is able to correctly calculate the number of `nodes` blocks in the resource even though the instances do not exist to begin with. But it can't do so when the spec changes in a way that causes the number of `nodes` blocks to change. And it always creates a plan where a singular `nodes` block should exist.

**Comment by rawmind0** [comment]
@loizoskounios , as mentioned, the issue is caused by the input data update during the provider execution. That's why is working fine when you apply again. The provider can't do nothing with that. `rke_cluster` should wait until all nodes are deployed, using some resource dependency or using tf modules.

**Comment by rawmind0** [comment]
Please, reopen issue if needed.
