### ISSUE TITLE
Failed to create Certificates deployer container on host

### ISSUE THREAD

**Issue by pawarsum** [rancher/terraform-provider-rke#248]
Getting below error while using version = "1.1.1",Terraform version =v0.13.0

terraform {
  required_providers {
    rke = {
      source  = "rancher/rke"
      version = "1.1.1"
    }
  }
}

Failed to create Docker container [cert-deployer] on host [XXX.XXX.XX.XX]: Error response from daemon: create \/etc/kubernetes: "\\/etc/kubernetes" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path]

Same can be deployed directly via rke command.

**Comment by rawmind0** [comment]
How looks like you rke_cluster definition??

**Comment by pawarsum** [comment]
resource "rke_cluster" "cluster" {
  nodes {
    address = module.nodes.public_ip
    internal_address = module.nodes.internal_ip
    user    = "dummy"
    role    = ["controlplane", "worker", "etcd"]
    ssh_key = file("~/.ssh/id_rsa")
  }
}

Version 1.1.0 works fine
terraform {
  required_providers {
    rke = {
      source  = "rancher/rke"
      version = "1.1.0"
    }
  }
}

**Comment by rawmind0** [comment]
That's weird. Successfully deployed and tested a bunch of clusters using provider 1.1.1 and tf 0.13.2

Are you reusing nodes?? If so, have you clean up them properly??

**Comment by magnus8672** [comment]
I am experiencing this same issue while utilizing the rancher deployment terraform from https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/  

I have stitched into another terraform project in order to deploy to an existing VPC where I intend to use rancher to control a bunch of other stuff. 

 Error response from daemon: create \/etc/kubernetes: "\\/etc/kubernetes"
includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path]

My invocation is the same as the above linked repo: 

resource "rke_cluster" "rancher_cluster" {
  cluster_name = "quickstart-rancher-server"

  nodes {
    address          = var.node_public_ip
    internal_address = var.node_internal_ip
    user             = var.node_username
    role             = ["controlplane", "etcd", "worker"]
    ssh_key          = var.ssh_private_key_pem
  }

  kubernetes_version = var.rke_kubernetes_version
}

**Comment by rawmind0** [comment]
I guess this is related with rke issue https://github.com/rancher/rke/issues/2232

**Comment by magnus8672** [comment]
Perhaps, but I was running this directly in AWS, not in VirtualBox or Windows.

**Comment by rawmind0** [comment]
@magnus8672 , i already read that you are trying to deploy [quickstart-aws-qs](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/) . I think the related issue is occurring when rke is deployed from windows client (same quickstart aws-qs is working fine for me), independently the deployment infra platform used. Are you deploying from a windows client?? 

Anyway, PR #254 is upgrading rke to v1.2.0 that should address the issue. May you please test it??

**Comment by pawarsum** [comment]
Tested with v1.1.3 , working fine. Thanks

**Comment by rawmind0** [comment]
Thanks for the feedback @pawarsum
