### ISSUE TITLE
dependencies for removing nodes

### ISSUE THREAD

**Issue by julienym** [rancher/terraform-provider-rke#256]
Hi,

Sorry if this seams like a newbie question, but I am stuck with a wrong order of execution on destroying nodes on a apply.

I use azurerm for provisionning the VMs and then rke (azurerm->rke) with the implicit dependancy between the 2 modules - even try the depends_on at the module level in TF 0.13.

The order is done correctly at the creation level, or even adding VM/node, but when we'd like to replaced or remove nodes, I was expecting TF to do a reverse order of execution (rke->azurerm) but it is not the case. 

I am wondering if it's a TF thing, or if it is something to improve in the rke/or azurerm provider ?

Thanks

**Comment by julienym** [comment]
See: https://github.com/rancher/terraform-provider-rke/issues/167

**Comment by rawmind0** [comment]
Hi @julienym , due to your explanation, i guess this is a question of module dependencies not the providers themself. 

> The order is done correctly at the creation level, or even adding VM/node, but when we'd like to replaced or remove nodes, I was expecting TF to do a reverse order of execution (rke->azurerm) but it is not the case.

This would be the expected behaviour within a tf provider, but using few providers as modules, it depends of the implementation. On the context of your example, i guess that the module (more or less) is deploying azure vm's (and may be other infra) and then the created vm's info is passed to rke provider, as `nodes` argument, isn't it?? If the tf module is doing something like that, rke provider `nodes` will not be updated until azure module do its job and update vms info.

**Comment by julienym** [comment]
Hi @rawmind0 , yes you assumed correctly. So it's the default behaviour. Thanks
