### ISSUE TITLE
Allow easy interaction with rke cluster without import

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [rancher/terraform-provider-rke#288]
Hello,

I wanted to use `kubernetes` provider with rke cluster and found this rke provider. I like how easy is to integrate rke cluster with `kubernetes` provider after provisioning a cluster with this provider but I couldn't find convenient way to configure `kubernetes` cluster without importing rke cluster into terraform. I thought about creating data source in this provider so it could be used like this:

```HCL
data "rke_cluster" "cluster" {
  cluster_yaml = file("clusters/dev-rke-pdx1/conf/rke.yml")
  update_only = true
}

provider "kubernetes" {
  host     = rke_cluster.cluster.api_server_url
  username = rke_cluster.cluster.kube_admin_user

  client_certificate     = rke_cluster.cluster.client_cert
  client_key             = rke_cluster.cluster.client_key
  cluster_ca_certificate = rke_cluster.cluster.ca_crt
}
```

**Comment by rawmind0** [comment]
Hello @mateuszkwiatkowski , the use case that you mention is not possible like that. All the data that you'd need to do it'd be at cluster rkestate file, so can't read this cluster data just with cluster_yaml file. So, rkestate file should also be provided and maintained with the last version on every tf execution to assure it's getting current cluster data.

Anyway, cluster import should be pretty straight forward, https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#import, managing rke cluster with this provider wouldn't  be an option for you??

**Comment by mateuszkwiatkowski** [comment]
Hi @rawmind0,
Many thanks for your response. You're right, final data resource should have this extra argument:
```
data "rke_cluster" "cluster" {
  cluster_yaml = file("rke.yml")
  cluster_state = file("rke.rkestate)
}
```

I'd like that it would return the same attributes as regular `rke_cluster` resource so that it's possible to easily integrate with such cluster with `kubernetes` provider and without full import to terraform. I'd like to still manage cluster with `rke` standalone binary because it's integrated with our other tools. Does that make sense to you?

**Comment by rawmind0** [comment]
I got your point @mateuszkwiatkowski , but i don't think that use a datasource like this would be a good approach. What happens if the rkestate file is not updated?? Wrong values may result from terraform apply. 

Anyway, if using this tf provider to manage the cluster is not an option for you, why not just generating and maintaining a single kubeconfig from rkestate and configure the kubernetes provider to use it, instead of managing and maintaining 2 local rke files (config and state)?? Maintain one local file avoiding the need of tf provider extra code sounds better than maintain 2 local files and the need to add tf provider extra code… and the result would be the same for this use case. What do you think??

```
# Instead of copy rke config and state files, just generate and copy kubeconfig
cat cluster.rkestate | jq -r '.currentState.certificatesBundle."kube-admin".config' > my_kube_config
```

```
provider "kubernetes" {
  config_path    = "my_kube_config"
  config_context = "<cluster_name>"
}
```

**Comment by rawmind0** [comment]
Please, reopen issue if required.
