### ISSUE TITLE
Continue releases for the rke 1.3.x branch

### ISSUE THREAD

**Issue by rheyser** [rancher/terraform-provider-rke#382]
RKE is supporting two distinct branches, 1.3.x and 1.4.y, for releases. Since 1.4 has decommissioned several older versions of kubernetes, it makes it impossible for teams that are still on older versions of kubernetes to upgrade. A release with the latest [1.3.18](https://github.com/rancher/rke/releases/tag/v1.3.18) (at the time of submission) code is still desirable for many users. Please continue to make releases on the 1.3.x branch (and also a new release would be nice).

**Comment by a-blender** [comment]
@rheyser We released the TFP RKE provider again https://github.com/rancher/terraform-provider-rke/releases/tag/v1.3.5 with support for RKE 1.3.19 on March 23 right after this issue was created. This version also supports k8s 1.24 clusters which now has an overlap with the 1.4.x line. As it stands, there is not enough customer demand to continue releasing on the 1.3.x branch but if demand rises, we will be on top of it.
