### ISSUE TITLE
[RFE] Add support for PodSecurityAdmissionConfigurationTemplate on K8s 1.26 clusters

### ISSUE THREAD

**Issue by git-ival** [rancher/terraform-provider-rke#399]
Currently the TFP RKE does not support setting PSA configuration on the creation of K8s 1.26 clusters.

In order to accomplish this it seems that a few things are needed:
  1. Update RKE to ~~1.4.4+~~ [1.4.8](https://github.com/rancher/rke/releases/tag/v1.4.8)
     - ~~There is an open PR for this: https://github.com/rancher/terraform-provider-rke/pull/397~~
  2. Add the PSA-related options to the `kube_api` service block defined in the RKE documentation
     - https://rke.docs.rancher.com/config-options/services/pod-security-admission

**Comment by slickwarren** [comment]
TODO for QA: create TFP automation ticket for PSACT

**Comment by a-blender** [comment]
Due to the reasons outlined [here](https://github.com/rancher/terraform-provider-rke/pull/416#issuecomment-1776215098), we will only be adding PSACT support for Method 1 (set pod_security_configuration) and Method 3 (use extra_args to pass a custom Admission Configuration file) for the provider. No customers are urgently asking for this and the latest version will be released OOB.

**Comment by a-blender** [comment]
# QA Test Template
  
# Problem


Currently the TFP RKE does not support setting PSA configuration on creation of K8s 1.25+ clusters.

# Solution


- [x]   1. Update RKE to [1.4.10](https://github.com/rancher/rke/releases/tag/v1.4.10
- [x]   2. Add the PSA-related options to the `kube_api` service block defined in the [RKE docs](https://rke.docs.rancher.com/config-options/services/pod-security-admission) method 1 `psa_security_configuration` and method 3 `extra_args`.
- [x] Update PSACT docs and add/update config examples
  
# Testing

 
## Engineering Testing

### Manual Testing


- [x] Method 1 - Pass restricted policy via the `kube-api.pod_security_configuration` field
```
services:
  kube-api:
    pod_security_configuration: restricted
```

Pass invalid value `pod_security_configuration: INVALID` and confirm provider throws a ValidateFunc error.

- [x] Method 3: Pass the path to an admission configuration file via `kube-api.extra_args.admission-control-config-file` and set `bind_mounts` to mount that file from the cluster node into the kube API server container

Per method 3, Docker has this lovely thing where [per the docs](https://docs.docker.com/storage/bind-mounts/),

```
The file or directory does not need to exist on the Docker host already. It is created on demand if it does not yet exist.
```

Yes, it creates it. ...as a directory.

So, in order to use kube API `extra_args` in TF to mount a custom admission configuration file to the API server you have to update the API server Dockerfile to touch an empty file so it exists already. Otherwise,

```
unable to read admission control configuration from \"<NODE PATH>/admission.yaml\" [read <CONTAINER PATH>/admission.yaml: is a directory]"
```

For TFP RKE, I just had to verify the provider is passing the extra arg `admission-control-config-file` correctly which it is.

### Automated Testing

 
## QA Testing Considerations

  
### Regressions Considerations

**Comment by a-blender** [comment]
We have moved our TFP RKE test process to use RCs like Rancher and the TF rancher2 provider. Please test this issue on RC [v1.4.3-rc1](https://github.com/rancher/terraform-provider-rke/releases/tag/v1.4.3-rc1). I will create additional RCs for all new code in scope.
