### ISSUE TITLE
Validate file paths for addons_include yaml file paths

### ISSUE THREAD

**Issue by weber-d** [rancher/terraform-provider-rke#99]
I want to use `addons_include` to automatically install some yamls for ingress-certs, psps and similar stuff. 

```yml
resource rke_cluster "cluster" {
    # ...
    addons_include = [
      "./k8s-addons/nginx-ingress-cert.yaml"
    ]
}
```

This doesn't work since I made a stupid mistake: The file was called `nginx-ingress-cert.yml`, so `.yml` instead of `.yaml`. Sadly this doesn't result in any error, neither on `terraform plan` nor `terraform apply`. 

Having those paths validated would be easier to troubleshoot, so an error occurs if specified files doesn't exist.

**Comment by linecolumn** [comment]
I do agree that file check should be in place but I've moved rke addons to kubernetes operator as addons are not supported by RKE anymore (unfortunately).

**Comment by yamamoto-febc** [comment]
Hi @weber-d ,

Sorry for delayed response, and thank you for your suggestion.
I think this is useful for users.

We will implement this soon:+1:

**Comment by iahmad-khan** [comment]
@linecolumn do you mean we should use kubernetes provider to install add-ons?

or we can just use kubectl apply -f on our own after cluster creation?

Currently I am doing correct paths but still its not installing it.

thanks

**Comment by rawmind0** [comment]
Long time from last update here and much provider and rke update. I don't know if still make sense this issue.

`addons_include` file path is already checked on rke v1.1.6 execution, https://github.com/rancher/rke/blob/v1.1.6/cluster/addons.go#L230 and error should be returned if not found. 

Anyway as an option, addons can be used instead of addons_include, and check the file with `addons = file("./k8s-addons/nginx-ingress-cert.yaml")` 

Please, reopen issue if needed, and sorry for the long delay
